pipeline {
    agent {label "machine"}
    stages {
        stage('Build') {
            steps {
               bat label: '', script: '''
cd merchantgalaxy
set JAVA_HOME="C:\\Program Files\\Java\\jdk-10"
echo $JAVA_HOME
 .\\gradlew.bat build
cd ..
@RD /S /Q merchantgalaxy
'''
            }
        }
        stage('Test')
        {
            steps {
                sh script: '''
                    echo "I am in Test step"
                ''',
            label: "Running Unit Test Cases"
            }
        }
        stage('Static Code Analysis')
        {
            steps {
                sh script: '''
                    echo "I am in Sonarqube scan"
                ''',
            label: "Running Sonarqube Scan"
            }
        }
        stage('Build DockerImage')
        {
            steps {
                sh script: '''
                    echo "I am Building DockerImage ="
                ''',
            label: "Building Docker Image"
            }
        }
        stage('Publish DockerImage')
        {
            steps {
                sh script: '''
                    echo "I am Pubishing DockerImage ="
                ''',
            label: "Publishing Docker Image"
            }
        }
    }
}
