pipeline {
    stages {
        stage('Build') {
            steps {
               sh script: '''
               cd merchantgalaxy
               echo "I am in build step"
               chmod +x gradlew
               ./gradlew build
               '''
            }
        }
        stage('Test')
        {
            steps {
                sh script: '''
                    echo "I am in Test step"
                    cd merchantgalaxy
                    ./gradlew test
                ''',
            label: "Running Unit Test Cases"
            }
        }
        stage('Static Code Analysis')
        {
            steps {
                sh script: '''
                    echo "I am in Sonarqube scan"
                ''',
            label: "Running Sonarqube Scan"
            }
        }
        stage('Build DockerImage')
        {
            agent {
                docker { image 'node:7-alpine' }
            }
    
            steps {
                sh script: '''
                    echo "I am Building DockerImage"
                    docker ps
                ''',
            label: "Building Docker Image"
            }
        }
        stage('Publish DockerImage')
        {
            steps {
                sh script: '''
                    echo "I am Pubishing DockerImage"
                ''',
            label: "Publishing Docker Image"
            }
        }
    }
}
