pipeline {
    agent any
    environment {
        registry = "gustavoapolinario/docker-test"
        registryCredential = 'dockerhub'
        dockerImage = ''
    }
    stages {
        stage('Build') {
            steps {
               sh script: '''
               cd merchantgalaxy
               echo "I am in build step."
               chmod +x gradlew
               ./gradlew build
               '''
            }
        }
        stage('Test')
        {
            steps {
                sh script: '''
                    echo "I am in Test step."
                    cd merchantgalaxy
                    ./gradlew test
                ''',
            label: "Running Unit Test Cases"
            }
        }
        stage('Static Code Analysis')
        {
            steps {
                sh script: '''
                    echo "I am in Sonarqube scan."
                ''',
            label: "Running Sonarqube Scan"
            }
        }
        stage('Build DockerImage')
        {
            steps {
                script {
                  docker.build registry + ":$BUILD_NUMBER"
                }
            }
        }
        stage('Publish DockerImage')
        {
            steps{
                script {
                    docker.withRegistry( '', registryCredential ) {
                        dockerImage.push()
                    }
                }
            }
        }
    }
}
